---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r libraries, echo = TRUE}
library(data.table)
library(lattice)
```

## Loading and preprocessing the data
```{r data-import, echo = TRUE}
activity <- data.table(read.csv("./activity.csv"))
```

## What is mean total number of steps taken per day?
```{r mean-total-number-steps, echo = TRUE}
# Calculate the total number of steps taken per day
steps_per_day <- activity[, .(steps_per_day = sum(steps)), by = "date"]
# Make a histogram of the total number of steps taken each day
histogram(data = steps_per_day, ~ steps_per_day, type = "density",
          xlab = "Number of steps taken per day", ylab = "Density")
# Calculate and report the mean and median of the total number of steps taken per day
cat("Mean steps per day: ", mean(steps_per_day$steps_per_day, na.rm = TRUE))
cat("Median steps per day: ", median(steps_per_day$steps_per_day, na.rm = TRUE))
```

## What is the average daily activity pattern?
```{r daily-activity, echo = TRUE}
# Make a time series plot (i.e. \color{red}{\verb|type = "l"|}type="l") of the
# 5-minute interval (x-axis) and the average number of steps taken, averaged
# across all days (y-axis)
daily_activity <- activity[, .(steps_per_interval = mean(steps, na.rm = TRUE))
                         , by = "interval"]
xyplot(data = daily_activity,
       steps_per_interval ~ interval, type = "l",
       xlab = "Interval",
       ylab = "Average steps per day")
# Which 5-minute interval, on average across all the days in the dataset,
# contains the maximum number of steps?
cat("Maximum average number of steps is",
    daily_activity[which.max(daily_activity$steps_per_interval), ]$steps_per_interval,
    "in interval",
    daily_activity[which.max(daily_activity$steps_per_interval), ]$interval)
```

## Imputing missing values
```{r missing-values, echo = TRUE}
# Calculate and report the total number of missing values in the dataset
# (i.e. the total number of rows with \color{red}{\verb|NA|}NAs)
cat(nrow(activity[is.na(steps)]), "rows contain NAs")
# 
testfunc <- function(x) {
  df <- x
  
}
```



## Are there differences in activity patterns between weekdays and weekends?
